### PR TITLE
Recent bug fixes

### LINKED ISSUE #32: Parallel by data: nemo.data merges data from top-level keys
If you run nemo with parallel:data using a data source where a sub-level key is the same as one of the other top-level keys, then nemo.data merges the identical keys, even though they're on separate levels:

#### data source:
```js
{
    "A": {
        "dataset": 1,
        "B": {
            "This should be the only property A can access under B": 1
        }
    },
    "B": {
        "dataset": 2
    }
}
```

#### minimal test code:
```js
console.log("dataset:", nemo.data.dataset);
console.log(nemo.data);
```

#### output:
```
// A case
dataset: 1
{ A:
   { dataset: 1,
     B: { 'This should be the only property A can access under B': 1 } },
  B:
   { dataset: 2,
     'This should be the only property A can access under B': 1 },
  dataset: 1 }

// B case
dataset: 2

{ A:
   { dataset: 1,
     B: { 'This should be the only property A can access under B': 1 } },
  B: { dataset: 2 },
  dataset: 2 }
```

In both cases, the data from inside `A` or `B` is available at the top level of `nemo.data`, but the `A` and `B` keys are also there. Since `A` has its own `B` property, it gets merged with the top-level `B` data.

When running parallel by data, I would expect `nemo.data` to only contain the data from each top-level key at a time, namely:

```
// A case

{
  "dataset": 1,
  "B": {
    "This should be the only property A can access under B": 1
  }
}

// B case
{
  "dataset": 2
}
```

### LINKED ISSUE #52: Plain JS config no longer merges top-level data
With the JSON config, a top-level `data` section would be merged with `nemo.data` at runtime, which was a neat way to set default data, even when running parallel by data:

```js
{
    "plugins": {
        "view": {
            "module": "nemo-view",
            "arguments": [
                "path:locator"
            ]
        }
    },
    "output": {
        "reports": "path:report"
    },
    "data": {
        "THIS_WILL_SHOW_UP_IN_NEMO_DATA": 1
    },
    "profiles": {
// etc.
```

With the plain JS config, top-level `data` doesn't get merged with the runtime nemo.data:

```js
const path = require("path");

module.exports = {
    plugins: {
        view: {
            module: "nemo-view"
        }
    },
    output: {
        reports: path.resolve("test/nemo2", "report")
    },
    data: {
        THIS_NEVER_SHOWS_UP_IN_NEMO_DATA: 1
    },
    profiles: {
        base: {
            tests: path.resolve("test/nemo2", "*test.js"),
            driver: {
                browser: "chrome"
            },
            data: {
                baseUrl: "https://www.google.com"
            },
            mocha: {
                timeout: 180000,
                reporter: "mochawesome",
                reporterOptions: {
                    quiet: true
                }
            }
        }
    }
};
```

### LINKED ISSUE #53: Plain JS config: How to load plugins?
The plain JS config example creates the plugin section as follows:

```js
module.exports = {
    plugins: {
        view: {
            module: "nemo-view"
        }
    },
```

But `nemo.view` is undefined:

```js
describe('@firstTest@', function () {
  it('should load a website', async function () {
    console.log('NEMO VIEW', this.nemo.view);
    await this.nemo.driver.get(this.nemo.data.baseUrl);
  });
});
```

Output:
```
NEMO VIEW undefined
```

I've tried both `module: require.resolve("nemo-view")` and `module: require("nemo-view")` but neither gets nemo-view to load.

Enabling `DEBUG=nemo-core:log` only shows `snap` being loaded:

```
nemo-core:log register plugin snap +0ms
  nemo-core:log plugin.registration fulfill with 1 plugins. +1ms
```

### PR DESCRIPTION
**Pull request by grawk**
- Fix #32: only merge "base" data in data/parallel mode if we aren't running "base" profile
- Fix #52: root data inclusion and override for plain JS config use case
- Fix #53: plugin configuration for plain JS config use case

### CODE REVIEW

**Comment by dwbruhn** [comment]
Awesome! Testing this out...

**Comment by grawk** [comment]
Thanks Dan. Let me know how it goes. Feel free to code review this PR as well :smile:

**Comment by dwbruhn** [comment]
Okay, regarding #32, just want to make sure I understand. Is the expectation that the whole base data will be merged into every parallel run of a non-base profile? Here's what I have in `nemo.config.js`. The base profile has all the data, while the chrome profile has none of its own.

```js
profiles: {
        base: {
            maxConcurrent: 1,
            tests: path.resolve("test/nemo2", "*test.js"),
            driver: {
                browser: "chrome"
            },
            mocha: {
                timeout: 180000,
                reporter: "mochawesome"
            },
            parallel: "data",
            data: {
                A: {
                    case: "A",
                    B: {
                        THIS_KEY_SHOULD_HAVE_NO_SIBLINGS_WHEN_UNDER_B: 1
                    }
                },
                B: {
                    case: "B"
                }
            }
        },
        chrome: {
            driver: {
                browser: "chrome"
            }
        }
    }
```

The test code:
```js
describe('@firstTest@', function () {
  it('should load a website', async function () {
    console.log("Running case", this.nemo.data.case);
    console.log("Data is:");
    console.log(JSON.stringify(this.nemo.data, null, 2));
  });
});
```

When running the base profile itself, the data is clean:

```
  @firstTest@
Running case A
Data is:
{
  "B": {
    "THIS_KEY_SHOULD_HAVE_NO_SIBLINGS_WHEN_UNDER_B": 1
  },
  "case": "A"
}
```

```
  @firstTest@
Running case B
Data is:
{
  "case": "B"
}
```

But with the chrome profile, the whole base data gets merged into every instance:

```
  @firstTest@
Running case A
Data is:
{
  "A": {
    "B": {
      "THIS_KEY_SHOULD_HAVE_NO_SIBLINGS_WHEN_UNDER_B": 1
    },
    "case": "A"
  },
  "B": {
    "THIS_KEY_SHOULD_HAVE_NO_SIBLINGS_WHEN_UNDER_B": 1,
    "case": "B"
  },
  "case": "A"
}
```

```
  @firstTest@
Running case B
Data is:
{
  "A": {
    "B": {
      "THIS_KEY_SHOULD_HAVE_NO_SIBLINGS_WHEN_UNDER_B": 1
    },
    "case": "A"
  },
  "B": {
    "case": "B"
  },
  "case": "B"
}
```

It's fine if that's expected. Just want to make sure I'm clear!

**Comment by grawk** [comment]
Yes, that's the expectation.. I think it's fair to ask for clear documentation on the data merge before accepting this PR :)

**Comment by dwbruhn** [comment]
Thanks! I was able to verify that this fixes all 3 issues.

**Comment by grawk** [comment]
Thanks @dwbruhn .. I'll work up a section on data config override behavior into the README .. Will ask that you take one last look at that tomorrow before merge/publish.

**Comment by dwbruhn** [comment]
@grawk Sure, just let me know! Looking forward to these fixes 😀

**Pull request merged**
