### PR TITLE
add switch for zeroExitCode even for failing tests

### PR DESCRIPTION
**Pull request by zzhengjian**
user can just add below setting to profile:base **"zeroExitCode": true,** to enable always zeroExitCode for nemo.

### CODE REVIEW

**Comment by zzhengjian** [comment]
Hi, @grawk  Can you take a review for this PR?

**Comment by grawk** [comment]
Hello @zzhengjian .. Sorry I was on vacation. Can you please
- consider whether we should check the actual value of the config if present (i.e. what are valid values and what is the behavior)
- add documentation for this flag to the README based on the above

**Comment by zzhengjian** [comment]
Hi, @grawk 
I've add the doc to README based on your comments, can you have a look and see if there's anything missing?

**Comment by zzhengjian** [comment]
Hi, @grawk
Can you please have a review and merge the PR if possible?

**Pull request merged**
